name: egg项目打包
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: build构建工作
    runs-on: ubuntu-latest

    steps:
    - name: 查询路径
      run: pwd
    - name: 查询npm版本
      run: npm --version
    - name: 读取仓库内容
      uses: actions/checkout@v4
    - name: 安装依赖，项目打包
      run: npm install
      run: npm run build

    - name: 部署github pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build